spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: ms-product
            uri: http://localhost:8081/
            predicates:
              - path=/products/**
          - id: ms-order
            uri: http://localhost:8082/
            predicates:
              - path=/orders/**
          - id: ms-payment
            uri: http://localhost:8083/
            predicates:
              - path=/payments/**
  application:
    name: gateway
server:
  port: 9090

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


