#spring:
#  application:
#    name: microservice-product
#  datasource:
#    url: jdbc:h2:mem:products-db
#  h2:
#    console:
#      enabled: true
#  cloud:
#    config:
#      enabled: false
#    discovery:
#      enabled: true
#server:
#  port: 8081

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
